common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: gopis_priorities_dev

test:
  <<: *common
  database: gopis_priorities_test